### PR TITLE
Run tests with CircleCI.

### PR DESCRIPTION
**Pull request by bfabio**
cc @libremente @sebbalex

### CODE REVIEW

**Comment by sebbalex** [comment]
This is definitely needed.

**Review by libremente — APPROVED** [review]

**Comment by bfabio** [comment]
@libremente I can't merge it, can you do it for me please? :)

**Comment by libremente** [comment]
I guess we should revert this now @bfabio

**Comment by bfabio** [comment]
@libremente Sounds fair, see #7.

**Pull request merged**
